name: skillogue
description: Skillogue

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  parse_server_sdk_flutter: ^3.1.3
  google_fonts: ^3.0.1
  flutter_rating_bar: ^4.0.1
  grouped_list: ^5.1.2
  multi_select_flutter: ^4.1.2
  flutter_launcher_icons: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo3.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"


