name: skillogue
description: Skillogue

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  grouped_list: ^5.1.2
  multi_select_flutter: ^4.1.2
  flutter_launcher_icons: ^0.11.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  auto_size_text: ^3.0.0
  curved_navigation_bar: ^1.0.3
  supabase_flutter: ^1.1.0
  google_nav_bar: ^5.0.6
  flex_color_picker: ^3.0.0
  flutter_speed_dial: ^6.2.0
  drop_down_list: ^0.0.4
  numberpicker: ^2.1.1
  random_avatar: ^0.0.7
  flutter_local_notifications: ^13.0.0
  flutter_localization: ^0.1.9
  onesignal_flutter: ^3.5.0

dev_dependencies:
  #flutter_test:
    #sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.22.1



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/languages/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo3.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"


