import 'dart:math';
import 'package:flutter/material.dart';

const keyApplicationId = 'xhYBShLQtWSlLo4BmLdK0QKvHiSFjwsAE36DeWnf';
const keyClientKey = '4gn52E4GHQDZOuDYQgw53YJpsBTcR8Yh6Fu5k1fQ';
const keyParseServerUrl = 'https://parseapi.back4app.com';

const searchIndex = 2;
const messagesIndex = 3;
const eventsIndex = 1;
const profileIndex = 0;

const appName = "SKILLOGUE";

const loggedProfileKey = 0;

const lastCountriesKey = 1;
const lastSkillsKey = 2;
const lastLanguagesKey = 3;
const lastGendersKey = 4;
const lastCityKey = 5;
const lastMinAge = 6;
const lastMaxAge = 7;

const newFunctionalityMessage =
    "Everyone wants the moon, but you gotta wait for this functionality! :-)";

Color getRandomDarkColor() {
  Color randomColor =
      Color((Random().nextDouble() * 0xFFFFFF).toInt()).withOpacity(1.0);
  if (randomColor.computeLuminance() < 0.250) {
    return randomColor;
  } else {
    return getRandomDarkColor();
  }
}

TextStyle getWhiteTextStyle() {
  return const TextStyle(color: Colors.white);
}

Color getLightBlue() {
  return const Color.fromRGBO(179, 217, 248, 0);
}

Color? myGrey = Colors.grey[900];

List<String> skills = [
  'Acting',
  'Animals',
  'Archeology',
  'Architecture',
  'Art',
  'Backpacking',
  'Bird watching',
  'Calligraphy ',
  'Camping',
  'Cinema',
  'Climbing',
  'Clubbing',
  'Cocktails',
  'Comics',
  'Computer Science',
  'Cooking',
  'Crochet',
  'Culture Exchange',
  'Cycling ',
  'Dancing',
  'Design',
  'Drawing',
  'Drugs',
  'Embroidery',
  'Engineering ',
  'Entomology',
  'Entrepreneurship ',
  'Fashion',
  'Fencing',
  'Fishing',
  'Football',
  'Gardening',
  'Geology',
  'Golf',
  'Guitar',
  'Gym',
  'Hiking',
  'History',
  'Horse Riding',
  'Hunting',
  'Jewellery making',
  'Jogging',
  'Kayaking',
  'Knitting',
  'Language Exchange',
  'Literature',
  'Maths',
  'Motorbikes',
  'Movies',
  'Museums',
  'Music',
  'Nature',
  'Painting',
  'Photography',
  'Piano',
  'Politics',
  'Psychology',
  'Reading',
  'Role-playing',
  'Running',
  'Sailing',
  'Science',
  'Shooting',
  'Skiing',
  'Smiting',
  'Socializing',
  'Spirituality',
  'Sport',
  'Sustainability',
  'Swimming',
  'Taxidermy',
  'Theatre',
  'Translation',
  'Traveling',
  'Video Editing',
  'Volunteering',
  'Walking',
  'Wood carving',
  'Yoga'
];
List<String> genders = ["Male", "Female", "Other"];

const STANDARD_OPACITY = 0.35;
TextStyle textFieldStyleWithOpacity =
    TextStyle(color: Colors.grey.withOpacity(0.9));

List<String> cities = [
  'A Coruna',
  'Aachen',
  'Aarhus',
  'Aba',
  'Abaete',
  'Abeokuta',
  'Aberdeen',
  'Abertawe',
  'Abha',
  'Abidjan',
  'Abu Dhabi',
  'Abuja',
  'Acapulco de Juarez',
  'Accra',
  'Ad Dammam',
  'Ad Diwaniyah',
  'Adachi',
  'Adana',
  'Addis Ababa',
  'Adelaide',
  'Aden',
  'Ado-Ekiti',
  'Agadir',
  'Agartala',
  'Ageoshimo',
  'Agra',
  'Aguascalientes',
  'Ahmadnagar',
  'Ahmedabad',
  'Ahvaz',
  'Ailan Mubage',
  'Aizawl',
  'Ajmer',
  'Akita',
  'Akola',
  'Akron',
  'Aksu',
  'Akure',
  'Al Basrah',
  "Al Bayda'",
  'Al Fallujah',
  'Al Fayyum',
  'Al Hillah',
  'Al Hillah',
  'Al Hudaydah',
  'Al Hufuf',
  'Al Jubayl',
  'Al Kharj',
  'Al Khubar',
  'Al Khums',
  'Al Kut',
  'Al Mansurah',
  'Al Minya',
  'Al Mubarraz',
  'Al Qatif',
  'Al `Amarah',
  'Al `Ayn',
  'Albany',
  'Albuquerque',
  'Aleppo',
  'Alexandria',
  'Algiers',
  'Alicante',
  'Aligarh',
  'Allahabad',
  'Allentown',
  'Almaty',
  'Almere',
  'Almeria',
  'Alor Setar',
  'Alwar',
  'Amagasaki',
  'Amarillo',
  'Ambon',
  'Americana',
  'Amman',
  'Amol',
  'Amravati',
  'Amritsar',
  'Amsterdam',
  'An Najaf',
  'An Nasiriyah',
  'Anaheim',
  'Ananindeua',
  'Anantapur',
  'Anapolis',
  'Anchorage',
  'Anda',
  'Andijon',
  'Angarsk',
  'Angeles City',
  'Anguo',
  'Anju',
  'Ankang',
  'Anlu',
  'Ann Arbor',
  'Annaba',
  'Anqing',
  'Anqiu',
  'Ansan',
  'Anshan',
  'Anshun',
  'Antananarivo',
  'Antioch',
  'Antipolo',
  'Antofagasta',
  'Antsirabe',
  'Antwerp',
  'Anyang',
  'Aomori',
  'Ap Da Loi',
  'Apapa',
  'Appleton',
  'Aqtobe',
  'Ar Ramadi',
  'Ar Raqqah',
  'Aracaju',
  'Arak',
  'Arakawa',
  'Arapiraca',
  'Araraquara',
  'Ardabil',
  'Arequipa',
  'Arica',
  'Arkhangelsk',
  'Arlington',
  'Arlington',
  'Armenia',
  'Arroyo Naranjo',
  'Arua',
  'Arusha',
  'As Samawah',
  'As Sib',
  'As Sulaymaniyah',
  'Asahikawa',
  'Asan',
  'Asansol',
  'Ashdod',
  'Asheville',
  'Asmara',
  'Astrakhan',
  'Asuncion',
  'Aswan',
  'Asyut',
  "At Ta'if",
  'Athens',
  'Atlanta',
  'Atlantic City',
  'Atsugicho',
  'Atushi',
  'Atyrau',
  'Auckland',
  'Augsburg',
  'Augusta',
  'Aurangabad',
  'Aurora',
  'Austin',
  'Avcilar',
  'Avondale',
  'Awasa',
  'Awka',
  'Az Zaqaziq',
  "Az Zarqa'",
  'Az Zubayr',
  'Ba`qubah',
  'Babol',
  'Babruysk',
  'Babylon',
  'Bac Lieu',
  'Bac Ninh',
  'Bacolod',
  'Bacoor',
  'Badalona',
  'Bafoussam',
  'Bagam',
  'Bagcilar',
  'Baghdad',
  'Bago',
  'Baguio City',
  'Bahar',
  'Bahawalpur',
  'Bahia Blanca',
  'Bahir Dar',
  'Baicheng',
  'Baicheng',
  'Baishan',
  'Baiyin',
  'Bakersfield',
  'Baku',
  'Balashikha',
  'Bali',
  'Balikpapan',
  'Baltimore',
  'Bamako',
  'Bamenda',
  'Bamiantong',
  'Banda Aceh',
  'Bandar Lampung',
  'Bandar `Abbas',
  'Bandung',
  'Banfield',
  'Bangalore',
  'Bangkok',
  'Bangui',
  'Banjarbaru',
  'Banjarmasin',
  'Baoding',
  'Baojishi',
  'Baoshan',
  'Baotou',
  'Barasat',
  'Barcelona',
  'Barcelona',
  'Barddhaman',
  'Bareilly',
  'Bari',
  'Barinas',
  'Barishal',
  'Barnaul',
  'Barnsley',
  'Barnstable',
  'Barquisimeto',
  'Barra do Dande',
  'Barrancabermeja',
  'Barranquilla',
  'Barueri',
  'Baruta',
  'Bata',
  'Batangas',
  'Batna',
  'Baton Rouge',
  'Bauchi',
  'Bauru',
  'Bayamo',
  'Bazhou',
  'Bazhou',
  'Beersheba',
  'Begusarai',
  'Beian',
  'Beichengqu',
  'Beidao',
  'Beihai',
  'Beijing',
  'Beining',
  'Beipiao',
  'Beira',
  'Beirut',
  'Bekasi',
  'Belas',
  'Belem',
  'Belfast',
  'Belgaum',
  'Belgorod',
  'Belgrade',
  'Bellary',
  'Bello',
  'Belo Horizonte',
  'Bengbu',
  'Benghazi',
  'Bengkulu',
  'Benguela',
  'Beni',
  'Benin City',
  'Benxi',
  'Bergen',
  'Berlin',
  'Betim',
  'Bezwada',
  'Bhagalpur',
  'Bharatpur',
  'Bhatinda',
  'Bhatpara',
  'Bhavnagar',
  'Bhilai',
  'Bhilwara',
  'Bhiwandi',
  'Bhopal',
  'Bhubaneshwar',
  'Bhuj',
  'Bialystok',
  'Bielefeld',
  'Bien Hoa',
  'Bijapur',
  'Bijiao',
  'Bijie',
  'Bikaner',
  'Bila Tserkva',
  'Bilaspur',
  'Bilbao',
  'Binan',
  'Binangonan',
  'Binjai',
  'Binxian',
  'Binzhou',
  'Biratnagar',
  'Birmingham',
  'Birmingham',
  'Bishkek',
  'Biskra',
  'Bissau',
  'Bitung',
  'Biysk',
  'Blagoveshchensk',
  'Blantyre',
  'Blida',
  'Bloemfontein',
  'Blumenau',
  'Bo',
  'Boa Vista',
  'Boaco',
  'Bobo-Dioulasso',
  'Bochum',
  'Bogor',
  'Bogota',
  'Boise',
  'Bole',
  'Bologna',
  'Bolton',
  'Bonita Springs',
  'Bonn',
  'Bor',
  'Bordeaux',
  'Borujerd',
  'Boston',
  'Botou',
  'Bouake',
  'Bozhou',
  'Bradford',
  'Brahmanbaria',
  'Brahmapur',
  'Brampton',
  'Brasilia',
  'Brasov',
  'Bratislava',
  'Bratsk',
  'Braunschweig',
  'Brazzaville',
  'Bremen',
  'Bremerton',
  'Brest',
  'Bridgeport',
  'Brisbane',
  'Bristol',
  'Brno',
  'Bronx',
  'Brookhaven',
  'Brooklyn',
  'Brownsville',
  'Brussels',
  'Bryansk',
  'Bucaramanga',
  'Bucharest',
  'Bucheon',
  'Budapest',
  'Buenaventura',
  'Buenos Aires',
  'Buffalo',
  'Bujumbura',
  'Bukavu',
  'Bukhara',
  'Bukit Mertajam',
  'Bulawayo',
  'Bunkyo-ku',
  'Buon Ma Thuot',
  'Buraydah',
  'Burgas',
  'Burnaby',
  'Bursa',
  'Burutu',
  'Busan',
  'Butembo',
  'Butterworth',
  'Butuan',
  'Bydgoszcz',
  'Ca Mau',
  'Cabanatuan City',
  'Cabimas',
  'Cabinda',
  'Cabuyao',
  'Cacuaco',
  'Caerdydd',
  'Cagayan de Oro',
  'Cainta',
  'Cairo',
  'Cajamarca',
  'Calabar',
  'Calgary',
  'Cali',
  'Calicut',
  'Callao',
  'Caloocan City',
  'Camacari',
  'Camaguey',
  'Campeche',
  'Campina Grande',
  'Campinas',
  'Campo Grande',
  'Campos',
  'Can Tho',
  'Canberra',
  'Cancun',
  'Cangzhou',
  'Canoas',
  'Canton',
  'Cape Coral',
  'Cape Town',
  'Caracas',
  'Carapicuiba',
  'Cariacica',
  'Carlos Manuel de Cespedes',
  'Carrefour',
  'Cartagena',
  'Cartagena',
  'Caruaru',
  'Casablanca',
  'Cascais',
  'Cascavel',
  'Catania',
  'Catia La Mar',
  'Caucaia',
  'Cawnpore',
  'Caxias do Sul',
  'Cebu City',
  'Celaya',
  'Cencheng',
  'Central Coast',
  'Centurion',
  "Ch'onan",
  "Ch'ongjin",
  'Chalco',
  'Chanda',
  'Chandigarh',
  'Chandler',
  "Chang'an",
  'Changchun',
  'Changde',
  'Changhua',
  'Changping',
  'Changsha',
  'Changsha',
  'Changshu',
  'Changwon',
  'Changzhi',
  'Changzhou',
  'Chaohucun',
  'Chaoyang',
  'Chaozhou',
  'Chapeco',
  'Charleroi',
  'Charleston',
  'Charlotte',
  'Chattanooga',
  'Chattogram',
  'Cheboksary',
  'Chelyabinsk',
  'Chemnitz',
  'Chengde',
  'Chengdu',
  'Chengguan',
  'Chengjiao',
  'Chengtangcun',
  'Chengxiang',
  'Chennai',
  'Chenzhou',
  'Cheongju',
  'Cherepovets',
  'Cherkasy',
  'Chernihiv',
  'Chernivtsi',
  'Chesapeake',
  'Chiayi',
  'Chiba',
  'Chicago',
  'Chiclayo',
  'Chifeng',
  'Chigasaki',
  'Chihuahua',
  'Chimalhuacan',
  'Chimbote',
  'Chimoio',
  'Chiniot',
  'Chinju',
  'Chishui',
  'Chisinau',
  'Chita',
  'Chitungwiza',
  'Chizhou',
  'Chofugaoka',
  'Choloma',
  'Chongqing',
  'Chongzuo',
  'Christchurch',
  'Chula Vista',
  'Chuncheon',
  'Chungju',
  'Chuxiong',
  'Chuzhou',
  'Cidade de Nacala',
  'Cilacap',
  'Cilegon',
  'Cimahi',
  'Cincinnati',
  'Cirebon',
  'City of Calamba',
  'City of Paranaque',
  'Ciudad Apodaca',
  'Ciudad Benito Juarez',
  'Ciudad Bolivar',
  'Ciudad General Escobedo',
  'Ciudad Guayana',
  'Ciudad Lopez Mateos',
  'Ciudad Nezahualcoyotl',
  'Ciudad Obregon',
  'Ciudad Santa Catarina',
  'Ciudad Victoria',
  'Ciudad del Este',
  'Cleveland',
  'Cluj-Napoca',
  'Coatepeque',
  'Coatzacoalcos',
  'Coban',
  'Cochabamba',
  'Coimbatore',
  'College Station',
  'Cologne',
  'Colombo',
  'Colombo',
  'Colon',
  'Colorado Springs',
  'Columbia',
  'Columbus',
  'Columbus',
  'Comayaguela',
  'Comilla',
  'Comodoro Rivadavia',
  'Conakry',
  'Concepcion',
  'Concord',
  'Concord',
  'Constanta',
  'Constantine',
  'Contagem',
  'Copenhagen',
  'Coquimbo',
  'Cordoba',
  'Cordoba',
  'Cordoba',
  'Cork',
  'Coro',
  'Corpus Christi',
  'Corrientes',
  'Cotabato',
  'Cotia',
  'Cotonou',
  'Coventry',
  'Craiova',
  'Cranbourne',
  'Crato',
  'Criciuma',
  'Cua',
  'Cubal',
  'Cucuta',
  'Cuddapah',
  'Cuenca',
  'Cuernavaca',
  'Cuiaba',
  'Culiacan',
  'Cumana',
  'Curepipe',
  'Curitiba',
  'Cusco',
  'Cuttack',
  'Czestochowa',
  'Dadukou',
  'Daegu',
  'Daejeon',
  'Dahuk',
  'Dakar',
  'Dalai',
  'Dali',
  'Dalian',
  'Dallas',
  'Daloa',
  'Damanhur',
  'Damascus',
  'Damaturu',
  'Damietta',
  'Dandong',
  'Dangyang',
  'Danjiangkou',
  'Danyang',
  'Daqing',
  'Dar es Salaam',
  'Dashiqiao',
  'Dasmarinas',
  'Dasoguz',
  'Datang',
  'Davangere',
  'Davao',
  'Davenport',
  'Dayan',
  'Daye',
  'Dayr az Zawr',
  'Dayton',
  'Dazhou',
  'Debrecen',
  'Dehra Dun',
  'Dehui',
  'Delhi',
  'Delmas',
  'Dengtacun',
  'Dengtalu',
  'Denov',
  'Denpasar',
  'Denton',
  'Denver',
  'Depok',
  'Dera Ghazi Khan',
  'Derby',
  'Des Moines',
  'Detroit',
  'Deyang',
  'Dezful',
  'Dezhou',
  'Dhaka',
  'Dhanbad',
  'Dhulia',
  'Diadema',
  'Diaobingshancun',
  'Dili',
  'Dindigul',
  'Dingxi',
  'Dingzhou',
  'Dire Dawa',
  'Divinopolis',
  'Djelfa',
  'Djibouti',
  'Djougou',
  'Dnipro',
  'Dodoma',
  'Doha',
  'Donetsk',
  'Dongguan',
  'Dongning',
  'Dongtai',
  'Dongyang',
  'Dortmund',
  'Douala',
  'Dresden',
  'Drug',
  'Dubai',
  'Dublin',
  'Duisburg',
  'Dumai',
  'Dunhua',
  'Durango',
  'Durban',
  'Durgapur',
  'Durham',
  'Dushanbe',
  'Dusseldorf',
  'Duyun',
  'Dzerzhinsk',
  'East London',
  'Ecatepec',
  'Edinburgh',
  'Edmonton',
  'Edogawa',
  'Eindhoven',
  'El Fasher',
  'El Kelaa des Srarhna',
  'El Obeid',
  'El Paso',
  'El Tigre',
  'Elazig',
  'Elche',
  'Ellore',
  'Eloy Alfaro',
  'Encheng',
  'Engels',
  'Ensenada',
  'Enugu',
  'Envigado',
  'Erbil',
  'Erfurt',
  'Esenler',
  'Esenyurt',
  'Esfahan',
  'Eslamshahr',
  'Espoo',
  'Essen',
  'Etawah',
  'Eugene',
  'Evansville',
  'Ezhou',
  'Faisalabad',
  'Fangchenggang',
  'Fangting',
  'Farg`ona',
  'Fargo',
  'Faridabad',
  'Fayetteville',
  'Fayetteville',
  'Feicheng',
  'Feira de Santana',
  'Fengcheng',
  'Fenyang',
  'Fes',
  'Firozabad',
  'Flint',
  'Florence',
  'Florencio Varela',
  'Florianopolis',
  'Floridablanca',
  'Fontana',
  'Formosa',
  'Fort Collins',
  'Fort Wayne',
  'Fort Worth',
  'Fort-de-France',
  'Fortaleza',
  'Foshan',
  'Foz do Iguacu',
  'Franca',
  'Frankfurt',
  'Freetown',
  'Freiburg im Breisgau',
  'Fremont',
  'Fresnillo',
  'Fresno',
  'Frisco',
  "Fu'an",
  'Fuchu',
  'Fuding',
  'Fuji',
  'Fujin',
  'Fujisawa',
  'Fukui',
  'Fukuoka',
  'Fukushima',
  'Fukuyama',
  'Fuqing',
  'Fuquan',
  'Fushun',
  'Fuxin',
  'Fuyang',
  'Fuyang',
  'Fuyuan',
  'Fuzhou',
  'Fuzhou',
  'Gabela',
  'Gaborone',
  'Gainesville',
  'Gaizhou',
  'Galati',
  'Ganca',
  'Ganda',
  'Gangneung',
  'Ganzhou',
  'Gaobeidian',
  'Gaomi',
  'Gaoping',
  'Gaoping',
  'Gaoyou',
  'Gaozhou',
  'Garland',
  'Garoua',
  'Gatineau',
  'Gaya',
  'Gdansk',
  'Gdynia',
  'Gedaref',
  'Gelsenkirchen',
  'General Santos',
  'General Trias',
  'Geneva',
  'Genoa',
  'Gent',
  'George Town',
  'Georgetown',
  'Ghaziabad',
  'Ghulja',
  'Gifu',
  'Gijon',
  'Gilbert',
  'Gimpo',
  'Giza',
  'Glasgow',
  'Glendale',
  'Goiania',
  'Gold Coast',
  'Golmud',
  'Goma',
  'Gombe',
  'Gomez Palacio',
  'Gonaives',
  'Gonder',
  'Gongzhuling',
  'Gonzalez Catan',
  'Gorakhpur',
  'Gorgan',
  'Gothenburg',
  'Governador Valadares',
  'Goyang',
  'Granada',
  'Grand Rapids',
  'Gravatai',
  'Graz',
  'Green Bay',
  'Greensboro',
  'Greenville',
  'Groningen',
  'Groznyy',
  'Guacara',
  'Guadalajara',
  'Guadalupe',
  'Guadalupe',
  "Guang'an",
  'Guangming',
  'Guangshui',
  'Guangyuan',
  'Guangzhou',
  'Guankou',
  'Guankou',
  'Guantanamo',
  'Guarenas',
  'Guaruja',
  'Guarulhos',
  'Guasave',
  'Guatemala City',
  'Guayaquil',
  'Gueckedou',
  'Guigang',
  'Guilin',
  'Guiping',
  'Guixi',
  'Guiyang',
  'Gujiao',
  'Gujranwala',
  'Gujrat',
  'Gulbarga',
  'Gulfport',
  'Gulou',
  'Gungoren',
  'Guntur',
  'Gusau',
  'Guwahati',
  'Guyuan',
  'Gwalior',
  'Gwangju',
  'Gwangmyeongni',
  'Gyeongsan',
  "Ha'il",
  'Hachinohe',
  'Hachioji',
  'Haeju',
  'Hafr al Batin',
  'Hai Duong',
  "Hai'an",
  'Haicheng',
  'Haifa',
  'Haikou',
  'Hailin',
  'Hailun',
  'Haiphong',
  'Hakodate',
  'Haldia',
  'Halifax',
  'Halle',
  'Halwan',
  'Hamadan',
  'Hamah',
  'Hamamatsu',
  'Hamburg',
  'Hamhung',
  'Hamilton',
  'Hancheng',
  'Hanchuan',
  'Handan',
  'Handwara',
  'Hangu',
  'Hangzhou',
  'Hannover',
  'Hanoi',
  'Hanzhong',
  'Haora',
  'Hapur',
  'Harare',
  'Harbin',
  'Harrisburg',
  'Hartford',
  'Hatay',
  'Havana',
  'Hebi',
  'Hechi',
  'Hefei',
  'Hegang',
  'Heihe',
  'Hejian',
  'Hejin',
  'Helixi',
  'Helsinki',
  'Hempstead',
  'Henderson',
  'Hengshui',
  'Hengyang',
  'Hengzhou',
  'Herat',
  'Hermosillo',
  'Heroica Matamoros',
  'Heroica Nogales',
  'Heshan',
  'Heyuan',
  'Heze',
  'Hezhou',
  'Hialeah',
  'Hickory',
  'Higashi-osaka',
  'Higuey',
  'Himeji',
  'Hirakata',
  'Hiratsuka',
  'Hirosaki',
  'Hiroshima',
  'Hisar',
  'Ho Chi Minh City',
  'Hobart',
  'Hohhot',
  'Holguin',
  'Homs',
  "Homyel'",
  'Honcho',
  'Hong Kong',
  "Hong'an",
  'Hongjiang',
  'Hongzhai',
  'Honolulu',
  'Horlivka',
  'Hortolandia',
  'Hospet',
  'Hotan',
  'Houston',
  'Hpa-An',
  'Hrodna',
  'Hsinchu',
  'Huacho',
  'Huadian',
  "Huai'an",
  'Huaibei',
  'Huaihua',
  'Huainan',
  'Huaiyin',
  'Huambo',
  'Huancayo',
  'Huanggang',
  'Huanghua',
  'Huanglongsi',
  'Huangshan',
  'Huangshi',
  'Huayin',
  'Huazhou',
  'Huazhou',
  'Hubli',
  'Hue',
  'Huichang',
  'Huilong',
  'Huixquilucan',
  'Huizhou',
  'Hulin',
  'Huludao',
  'Hunchun',
  'Huntington',
  'Huntsville',
  'Huozhou',
  'Huzhou',
  'Hwasu-dong',
  'Hyderabad',
  'Hyderabad City',
  'Iasi',
  'Ibadan',
  'Ibague',
  'Ibaraki',
  'Ibb',
  'Ibb',
  'Ica',
  "Ich'on",
  'Ichalkaranji',
  'Ichihara',
  'Ichikawa',
  'Ichinomiya',
  'Iguacu',
  'Ijebu-Ode',
  'Ikare',
  'Ikeja',
  'Iksan',
  'Ile-Ife',
  'Iligan',
  'Iloilo',
  'Ilorin',
  'Imperatriz',
  'Imphal',
  'Imus',
  'Incheon',
  'Indaiatuba',
  'Indianapolis',
  'Indio',
  'Indore',
  'Ingraj Bazar',
  'Ipatinga',
  'Ipoh',
  'Ipswich',
  'Iquitos',
  'Irapuato',
  'Irbid',
  'Irkutsk',
  'Irvine',
  'Irving',
  'Isesaki',
  'Iskenderun',
  'Islamabad',
  'Islip',
  'Ismailia',
  'Istanbul',
  'Itabashi',
  'Itaborai',
  'Itabuna',
  'Itagui',
  'Itapevi',
  'Itaquaquecetuba',
  'Ivano-Frankivsk',
  'Ivanovo',
  'Iwaki',
  'Iwo',
  'Ixtapaluca',
  'Izhevsk',
  'Izmir',
  'Jabalpur',
  'Jaboatao',
  'Jacarei',
  'Jackson',
  'Jacksonville',
  'Jacobabad',
  'Jaipur',
  'Jakarta',
  'Jalalabad',
  'Jalandhar',
  'Jalgaon',
  'Jalingo',
  'Jambi',
  'Jammu',
  'Jamnagar',
  'Jamshedpur',
  'Jayapura',
  'Jeddah',
  'Jeju',
  'Jember',
  'Jeonju',
  'Jerez de la Frontera',
  'Jersey City',
  'Jerusalem',
  'Jessore',
  'Jhang City',
  'Jhansi',
  "Ji'an",
  "Ji'an Shi",
  'Jiaji',
  'Jiamusi',
  "Jian'ou",
  'Jiangguanchi',
  'Jiangjiafan',
  'Jiangmen',
  'Jianguang',
  'Jiangyin',
  'Jiannan',
  'Jianshe',
  'Jiaojiangcun',
  'Jiaozhou',
  'Jiaozuo',
  'Jiaxing',
  'Jiayuguan',
  'Jieshou',
  'Jiexiu',
  'Jieyang',
  'Jilin',
  "Jin'e",
  'Jinan',
  'Jinchang',
  'Jincheng',
  'Jingcheng',
  'Jingdezhen',
  'Jinghong',
  'Jingling',
  'Jinhua',
  'Jining',
  'Jining',
  'Jinshi',
  'Jinzhou',
  'Jitpur',
  'Jiujiang',
  'Jiutai',
  'Jixi',
  'Joao Pessoa',
  'Jodhpur',
  'Johannesburg',
  'Johor Bahru',
  'Joinvile',
  'Jos',
  'Jose C. Paz',
  'Juarez',
  'Juazeiro',
  'Juazeiro do Norte',
  'Juba',
  'Juiz de Fora',
  'Juliaca',
  'Junagadh',
  'Jundiai',
  'Jurong',
  'Kabankalan',
  'Kabul',
  'Kaduna',
  "Kaech'on",
  'Kaesong',
  'Kafr ad Dawwar',
  'Kagithane',
  'Kagoshima',
  'Kaifeng Chengguanzhen',
  'Kaihua',
  'Kaiyuan',
  'Kaiyuan',
  'Kaiyuan',
  'Kakinada',
  'Kakogawacho-honmachi',
  'Kalamazoo',
  'Kalemie',
  'Kaliningrad',
  'Kaluga',
  'Kalyan',
  'Kamarhati',
  'Kamianske',
  'Kampala',
  'Kananga',
  'Kanazawa',
  'Kandahar',
  'Kanggye',
  'Kano',
  'Kansas City',
  'Kaohsiung',
  'Karachi',
  'Karaj',
  'Karamay',
  "Karbala'",
  'Karimnagar',
  'Karlsruhe',
  'Karnal',
  'Kashan',
  'Kashgar',
  'Kashiwa',
  'Kassala',
  'Kassel',
  'Kasugai',
  'Kasukabe',
  'Kasur',
  'Kathmandu',
  'Katowice',
  'Katsina',
  'Katsushika-ku',
  'Kaunas',
  'Kawagoe',
  'Kawaguchi',
  'Kawasaki',
  'Kazan',
  'Kediri',
  'Keelung',
  'Kemerovo',
  'Kendari',
  'Kenitra',
  'Kennewick',
  'Kerman',
  'Kermanshah',
  'Khabarovsk',
  'Kharagpur',
  'Kharkiv',
  'Khartoum',
  'Khartoum North',
  'Kherson',
  'Khimki',
  'Khmelnytskyi',
  'Khomeyni Shahr',
  'Khorramabad',
  'Khulna',
  'Kiel',
  'Kigali',
  'Kikwit',
  'Killeen',
  'Kingston',
  'Kingston upon Hull',
  'Kinshasa',
  'Kirkuk',
  'Kirov',
  'Kisangani',
  'Kissimmee',
  'Kisumu',
  'Kita-ku',
  'Kitakyushu',
  'Kitchener',
  'Kitwe',
  'Klang',
  'Knoxville',
  'Kobe',
  'Kocaeli',
  'Kochi',
  'Kochi',
  'Kolhapur',
  'Kolkata',
  'Kolpino',
  'Kolwezi',
  "Komsomol'sk-na-Amure",
  'Konak',
  'Korhogo',
  'Koriyama',
  'Korla',
  'Korolev',
  'Koshigaya',
  'Kosice',
  'Kostroma',
  'Kota',
  'Kota Bharu',
  'Kota Kinabalu',
  'Koto-ku',
  'Krakow',
  'Krasnodar',
  'Krasnoyarsk',
  'Krefeld',
  'Kremenchuk',
  'Kropyvnytskyi',
  'Kryvyi Rih',
  'Kuaidamao',
  'Kuala Lumpur',
  'Kuala Terengganu',
  'Kuantan',
  'Kuching',
  'Kucukcekmece',
  'Kuiju',
  'Kumamoto',
  'Kumasi',
  'Kumul',
  'Kunduz',
  'Kunming',
  "Kunp'o",
  'Kunsan',
  'Kupang',
  'Kuqa',
  'Kurashiki',
  'Kure',
  'Kurgan',
  'Kurmuk',
  'Kurnool',
  'Kursk',
  'Kurume',
  'Kusti',
  'Kutahya',
  'Kuwait City',
  'Kyiv',
  'Kyongju',
  'Kyoto',
  'La Florida',
  'La Guaira',
  'La Paz',
  'La Paz',
  'La Vega',
  'La Victoria',
  'Lafayette',
  'Lafia',
  'Lagos',
  'Lahore',
  'Laibin',
  'Laiwu',
  'Laixi',
  'Laiyang',
  'Lakeland',
  'Lancaster',
  'Lancaster',
  'Langfang',
  'Langzhong',
  'Lansing',
  'Lanus',
  'Lanxi',
  'Lanzhou',
  'Laohekou',
  'Lapu-Lapu City',
  'Laredo',
  'Larkana',
  'Las Condes',
  'Las Palmas',
  'Las Pinas City',
  'Las Tunas',
  'Las Vegas',
  'Lashkar Gah',
  'Latakia',
  'Latur',
  'Laval',
  'Lecheng',
  'Leeds',
  'Legazpi City',
  'Leicester',
  'Leipzig',
  'Leiyang',
  'Leizhou',
  'Leling',
  'Lengshuijiang',
  'Leon de los Aldama',
  'Leping',
  'Leshan',
  'Lexington',
  'Lhasa',
  'Liangshi',
  'Lianjiang',
  'Lianran',
  'Lianshan',
  'Lianyuan',
  'Lianzhou',
  'Liaocheng',
  'Liaoyang',
  'Liaoyuan',
  'Libreville',
  'Licheng',
  'Licheng',
  'Lichuan',
  'Likasi',
  'Lille',
  'Lilongwe',
  'Lima',
  'Limassol',
  'Limbe',
  'Limeira',
  'Lincang',
  'Lincoln',
  'Linfen',
  'Lingbao Chengguanzhen',
  'Linghai',
  'Lingyuan',
  'Linhai',
  'Linxia Chengguanzhen',
  'Linyi',
  'Linz',
  'Lipa City',
  'Lipetsk',
  'Lisbon',
  'Lishui',
  'Little Rock',
  'Liuzhou',
  'Liverpool',
  'Ljubljana',
  'Lobito',
  'Lodz',
  'Lome',
  'London',
  'London',
  'Londrina',
  'Long Beach',
  'Long Xuyen',
  'Longba',
  'Longjin',
  'Longueuil',
  'Longyan',
  'Longzhou',
  'Los Alcarrizos',
  'Los Angeles',
  'Los Mochis',
  'Los Teques',
  'Loudi',
  'Louisville',
  'Loures',
  "Lu'an",
  'Luanda',
  'Luanzhou',
  'Lubango',
  'Lubbock',
  'Lubeck',
  'Lublin',
  'Lubuklinggau',
  'Lubumbashi',
  'Lucena',
  'Lucknow',
  'Ludhiana',
  'Luhansk',
  'Luocheng',
  'Luocheng',
  'Luofeng',
  'Luohe',
  'Luoyang',
  'Lusaka',
  'Luton',
  'Lutsk',
  'Luxor',
  'Luzhou',
  'Lviv',
  'Lyon',
  "Ma'anshan",
  'Mabalacat',
  'Macae',
  'Macapa',
  'Macau',
  'Maceio',
  'Machala',
  'Macheng',
  'Machida',
  'Madan',
  'Madison',
  'Madrid',
  'Madurai',
  'Maebashi',
  'Magdeburg',
  'Mage',
  'Magnitogorsk',
  'Mahilyow',
  "Mai'Adua",
  'Maiduguri',
  'Mainz',
  'Maipu',
  'Majene',
  'Makassar',
  'Makati City',
  'Makhachkala',
  'Makiivka',
  'Malabon',
  'Malaga',
  'Malang',
  'Malard',
  'Malegaon',
  'Malmo',
  'Malolos',
  'Manado',
  'Managua',
  'Manaus',
  'Manchester',
  'Mandalay',
  'Mandaluyong City',
  'Mandaue City',
  'Mandi Burewala',
  'Mangalore',
  'Manhattan',
  'Manila',
  'Manisa',
  'Manizales',
  'Mannheim',
  'Manta',
  'Manukau City',
  'Manzhouli',
  'Maoming',
  'Maputo',
  'Mar del Plata',
  'Maraba',
  'Maracaibo',
  'Maracanau',
  'Maracay',
  'Maradi',
  'Marawi City',
  'Mardan',
  'Marg`ilon',
  'Marikina City',
  'Marilao',
  'Marilia',
  'Maringa',
  'Mariupol',
  'Marka',
  'Markham',
  'Maroua',
  'Marrakech',
  'Marseille',
  'Mary',
  'Masan',
  'Maseru',
  'Mashhad',
  'Matadi',
  'Mataram',
  'Mathura',
  'Matola',
  'Matrah',
  'Matsudo',
  'Matsue',
  'Matsumoto',
  'Matsuyama',
  'Maturin',
  'Maua',
  'Mazabuka',
  'Mazar-e Sharif',
  'Mazatlan',
  'Mbale',
  'Mbandaka',
  'Mbeya',
  'Mbuji-Mayi',
  'McAllen',
  'McKinney',
  'Mecca',
  'Medan',
  'Medellin',
  'Medina',
  'Meerut',
  'Meguro',
  'Meicheng',
  'Meihekou',
  'Meishan',
  'Meishan',
  'Meizhou',
  'Mekele',
  'Meknes',
  'Melaka',
  'Melbourne',
  'Memphis',
  'Menongue',
  'Merida',
  'Merida',
  'Merlo',
  'Meru',
  'Mesa',
  'Messina',
  'Mexicali',
  'Mexico City',
  'Meycauayan',
  'Miami',
  'Mianyang',
  'Milan',
  'Milton Keynes',
  'Miluo Chengguanzhen',
  'Milwaukee',
  'Minamisuita',
  'Minatitlan',
  'Minato',
  'Mingguang',
  'Minna',
  'Minneapolis',
  'Minsk',
  'Minzhu',
  'Miri',
  'Mirpur Khas',
  'Mirzapur',
  'Mishan',
  'Misratah',
  'Mission Viejo',
  'Mississauga',
  'Mito',
  'Miyazaki',
  'Mizhou',
  'Mobile',
  'Mocamedes',
  'Modesto',
  'Mogadishu',
  'Mogi das Cruzes',
  'Mohammedia',
  'Mokpo',
  'Mombasa',
  'Monchengladbach',
  'Monclova',
  'Monrovia',
  'Monteria',
  'Monterrey',
  'Montes Claros',
  'Montevideo',
  'Montgomery',
  'Montpellier',
  'Montreal',
  'Monywa',
  'Moradabad',
  'Morelia',
  'Moreno Valley',
  'Morioka',
  'Morogoro',
  'Moscow',
  'Mossoro',
  'Mostoles',
  'Mosul',
  'Mubi',
  'Mudanjiang',
  'Multan',
  'Mumbai',
  'Munich',
  'Munster',
  'Muntinlupa City',
  'Murcia',
  'Murmansk',
  'Murrieta',
  'Muscat',
  'Muzaffarpur',
  'Mwanza',
  'Myeik',
  'Myitkyina',
  'Mykolaiv',
  'Mymensingh',
  'Myrtle Beach',
  'Mysore',
  'Mytishchi',
  "N'Djamena",
  'Naberezhnyye Chelny',
  'Nada',
  'Nadiad',
  'Naga City',
  'Nagano',
  'Nagaoka',
  'Nagareyama',
  'Nagasaki',
  'Nagercoil',
  'Nagoya',
  'Nagpur',
  'Nagqu',
  'Naha',
  'Naihati',
  'Nairobi',
  'Najafabad',
  'Nakano',
  'Nakuru',
  'Nalchik',
  'Nam Dinh',
  'Namangan',
  'Nampo',
  'Nampula',
  'Nanchang',
  'Nanchong',
  'Nanded',
  'Nangandao',
  'Nangong',
  'Nanjing',
  'Nanning',
  'Nanping',
  'Nantes',
  'Nantong',
  'Nanyang',
  'Naples',
  'Nara',
  'Narayanganj',
  'Nashua',
  'Nashville',
  'Nasik',
  'Nasim Shahr',
  'Nassau',
  'Natal',
  'Natal',
  'Naucalpan de Juarez',
  'Navotas',
  'Nawabshah',
  'Nay Pyi Taw',
  'Nazret',
  'Ndola',
  'Nehe',
  'Neijiang',
  'Neiva',
  'Nellore',
  'Nerima',
  'Netanya',
  'Neuquen',
  'New Delhi',
  'New Haven',
  'New Orleans',
  'New York',
  'Newark',
  'Newcastle',
  'Neya',
  'Neyshabur',
  'Nezahualcoyotl',
  'Nha Trang',
  'Niagara Falls',
  'Niamey',
  'Nice',
  'Nicosia',
  'Niigata',
  "Ning'an",
  'Ningbo',
  'Ningde',
  'Nishinomiya-hama',
  'Nishitokyo',
  'Niteroi',
  'Nizamabad',
  'Nizhnekamsk',
  'Nizhnevartovsk',
  'Nizhniy Novgorod',
  'Nizhniy Tagil',
  'Nogales',
  'Noginsk',
  'Nonthaburi',
  'Norfolk',
  'North Hempstead',
  'North Las Vegas',
  'North Port',
  'Northampton',
  'Northcote',
  'Norwich',
  'Nottingham',
  'Nouakchott',
  'Novi Sad',
  'Novo Hamburgo',
  'Novokuznetsk',
  'Novorossiysk',
  'Novosibirsk',
  'Nuevo Laredo',
  'Nukus',
  'Nur-Sultan',
  'Nuremberg',
  'Nyala',
  'Nyanza',
  'Oakashicho',
  'Oakland',
  'Oaxaca',
  'Oberhausen',
  'Odesa',
  'Ogbomoso',
  'Ogden',
  'Oita',
  'Okara',
  'Okayama',
  'Okazaki',
  'Oklahoma City',
  'Olinda',
  'Olongapo',
  'Olympia',
  'Omaha',
  'Omdurman',
  'Omsk',
  'Ondo',
  'Ongole',
  'Onitsha',
  'Oral',
  'Oran',
  'Orel',
  'Orenburg',
  'Orizaba',
  'Orlando',
  'Ormoc',
  'Orsk',
  'Orumiyeh',
  'Oruro',
  'Oruro',
  'Osaka',
  'Osan',
  'Osasco',
  'Osh',
  'Oskemen',
  'Oslo',
  'Osogbo',
  'Ostrava',
  'Ota',
  'Ota-ku',
  'Otsu',
  'Ottawa',
  'Ouagadougou',
  'Oujda-Angad',
  'Oulu',
  'Oviedo',
  'Owerri',
  'Owo',
  'Oxnard',
  'Oyo',
  'Oyster Bay',
  "P'yong-dong",
  'Pachuca',
  'Padang',
  'Padangsidempuan',
  'Padova',
  'Pagadian',
  'Paju',
  'Pakdasht',
  'Palangkaraya',
  'Palembang',
  'Palermo',
  'Palermo',
  'Pali',
  'Palm Bay',
  'Palm Coast',
  'Palma',
  'Palmas',
  'Palmira',
  'Palu',
  'Pamplona',
  'Panabo',
  'Panama City',
  'Panihati',
  'Panipat',
  'Panshi',
  'Paradise',
  'Paramaribo',
  'Parana',
  'Parbhani',
  'Paris',
  'Parnamirim',
  'Pasay City',
  'Pasig City',
  'Pasto',
  'Pathein',
  'Patiala',
  'Patna',
  'Paulista',
  'Pavlodar',
  'Pekalongan',
  'Pekanbaru',
  'Pelotas',
  'Pematangsiantar',
  'Pencheng',
  'Pendik',
  'Pensacola',
  'Penza',
  'Peoria',
  'Pereira',
  'Perm',
  'Perth',
  'Peshawar',
  'Petah Tiqwa',
  'Petaling Jaya',
  'Petion-Ville',
  'Petrolina',
  'Petropavl',
  'Petropolis',
  'Petrozavodsk',
  'Phan Thiet',
  'Philadelphia',
  'Phnom Penh',
  'Phoenix',
  'Pietermaritzburg',
  'Pikine',
  'Pingdingshan',
  'Pingdu',
  'Pinghu',
  'Pingliang',
  'Pingtung',
  'Pingxiang',
  'Pingzhen',
  'Piracicaba',
  'Pittsburgh',
  'Piura',
  'Pizhou',
  'Plano',
  'Playa del Carmen',
  'Ploiesti',
  'Plovdiv',
  'Plymouth',
  'Podolsk',
  'Pohang',
  'Pointe-Noire',
  'Pokhara',
  'Polokwane',
  'Poltava',
  'Ponta Grossa',
  'Pontianak',
  'Popayan',
  'Porbandar',
  'Port Elizabeth',
  'Port Harcourt',
  'Port Moresby',
  'Port Said',
  'Port St. Lucie',
  'Port Sudan',
  'Port-au-Prince',
  'Portland',
  'Portland',
  'Porto',
  'Porto Alegre',
  'Porto Velho',
  'Porto-Novo',
  'Portoviejo',
  'Portsmouth',
  'Posadas',
  'Poughkeepsie',
  'Poza Rica de Hidalgo',
  'Poznan',
  'Prague',
  'Praia Grande',
  'Presidente Prudente',
  'Pretoria',
  'Probolinggo',
  'Providence',
  'Provo',
  'Pskov',
  'Pucallpa',
  'Pudong',
  'Puducherry',
  'Puebla',
  'Puente Alto',
  'Puerto Cabello',
  'Puerto La Cruz',
  'Puerto Princesa',
  'Puerto Vallarta',
  'Pune',
  'Puning',
  'Punto Fijo',
  'Puqi',
  'Puri',
  'Purnea',
  'Putian',
  'Puxi',
  'Puyang',
  'Puyang Chengguanzhen',
  'Pyeongtaek',
  'Pyongyang',
  "Qa'em Shahr",
  'Qamdo',
  'Qaraghandy',
  'Qarchak',
  'Qarshi',
  'Qazvin',
  "Qian'an",
  'Qianxi',
  'Qianzhou',
  'Qina',
  'Qinbaling',
  'Qincheng',
  'Qingdao',
  'Qingnian',
  'Qingping',
  'Qingyang',
  'Qingyuan',
  'Qingzhen',
  'Qingzhou',
  'Qinhuangdao',
  'Qinzhou',
  'Qionghu',
  'Qiqihar',
  'Qom',
  'Qoqon',
  'Qostanay',
  'Quang Ha',
  'Quang Ngai',
  'Quanzhou',
  'Quebec City',
  'Queens',
  'Queretaro',
  'Quetta',
  'Quetzaltenango',
  'Quezon City',
  'Qufu',
  'Quilmes',
  'Quilon',
  'Quito',
  'Qujing',
  'Quy Nhon',
  'Quzhou',
  'Qyzylorda',
  'Rabat',
  'Rach Gia',
  'Radom',
  'Rahimyar Khan',
  'Raichur',
  'Raipur',
  'Rajahmundry',
  'Rajapalaiyam',
  'Rajkot',
  'Rajshahi',
  'Raleigh',
  'Ramgundam',
  'Rampur',
  'Rancagua',
  'Ranchi',
  'Randburg',
  'Rangoon',
  'Rangpur',
  'Rasht',
  'Ratlam',
  'Raurkela',
  'Rawalpindi',
  'Reading',
  'Recife',
  'Regina',
  'Rennes',
  'Reno',
  'Renqiu',
  'Resistencia',
  'Reynosa',
  'Ribeirao Preto',
  'Ribeirao das Neves',
  'Richmond',
  'Riga',
  'Rio Branco',
  'Rio de Janeiro',
  'Rishon LeZiyyon',
  'Riverside',
  'Rivne',
  'Riyadh',
  'Rizhao',
  'Roanoke',
  'Rochester',
  'Rockford',
  'Rodriguez',
  'Rohtak',
  'Rome',
  'Rondonopolis',
  'Rongcheng',
  'Rongcheng',
  'Rongjiawan',
  'Roodepoort',
  'Rosario',
  'Rostock',
  'Rostov',
  'Rotterdam',
  'Round Lake Beach',
  'Rucheng',
  'Rufisque',
  "Rui'an",
  'Ruiming',
  'Ryazan',
  'Sa Dec',
  'Sabadell',
  'Sabzevar',
  'Sacramento',
  'Safi',
  'Saga',
  'Sagamihara',
  'Saharanpur',
  'Sahiwal',
  'Saidpur',
  'Saidu Sharif',
  'Saint Petersburg',
  'Saitama',
  'Sakai',
  'Sakarya',
  'Salamanca',
  'Sale',
  'Salem',
  'Salem',
  'Salt Lake City',
  'Salta',
  'Saltillo',
  'Salvador',
  'Samara',
  'Samarinda',
  'Samarkand',
  'Sambalpur',
  'Sambhal',
  'San Antonio',
  'San Bernardino',
  'San Bernardo',
  'San Carlos City',
  'San Cristobal',
  'San Cristobal',
  'San Diego',
  'San Felipe',
  'San Fernando',
  'San Francisco',
  'San Jose',
  'San Jose',
  'San Jose del Monte',
  'San Juan',
  'San Juan',
  'San Juan del Rio',
  'San Lorenzo',
  'San Luis Potosi',
  'San Mateo',
  'San Miguel',
  'San Miguel de Tucuman',
  'San Miguelito',
  'San Nicolas de los Garza',
  'San Pablo',
  'San Pedro',
  'San Pedro Carcha',
  'San Pedro Sula',
  'San Salvador',
  'San Salvador de Jujuy',
  'San-Pedro',
  'Sanaa',
  'Sanandaj',
  'Sandakan',
  'Sandton',
  'Sangli',
  'Sanhe',
  'Sanmenxia',
  'Sanming',
  'Sannai',
  'Santa Ana',
  'Santa Ana',
  'Santa Barbara',
  'Santa Clara',
  'Santa Clarita',
  'Santa Cruz',
  'Santa Cruz',
  'Santa Fe',
  'Santa Maria',
  'Santa Maria',
  'Santa Marta',
  'Santa Rosa',
  'Santa Rosa',
  'Santa Teresa del Tuy',
  'Santarem',
  'Santiago',
  'Santiago',
  'Santiago de Cuba',
  'Santiago del Estero',
  'Santo Andre',
  'Santo Domingo',
  'Santo Domingo Este',
  'Santo Domingo de los Colorados',
  'Santo Tomas',
  'Santos',
  'Sanya',
  'Sanzhou',
  'Sao Bernardo do Campo',
  'Sao Carlos',
  'Sao Goncalo',
  'Sao Jose do Rio Preto',
  'Sao Jose dos Campos',
  'Sao Jose dos Pinhais',
  'Sao Leopoldo',
  'Sao Luis',
  'Sao Paulo',
  'Sao Vicente',
  'Sapele',
  'Sapporo',
  'Sarajevo',
  'Saransk',
  'Sarasota',
  'Saratov',
  'Sargodha',
  'Sariwon',
  'Sarta',
  'Sasebo',
  'Saskatoon',
  'Saugor',
  'Saurimo',
  'Savannah',
  'Saveh',
  'Scottsdale',
  'Scranton',
  'Seattle',
  'Secunderabad',
  'Sekondi',
  'Semarang',
  'Semey',
  'Sendai',
  'Seoul',
  'Serang',
  'Seremban',
  'Serra',
  'Setagaya',
  'Sete Lagoas',
  'Setif',
  'Sevastopol',
  'Sevilla',
  'Sfax',
  'Shache',
  'Shah Alam',
  'Shahe',
  'Shahjanpur',
  'Shahr-e Qods',
  'Shahriar',
  'Shakhty',
  'Shanghai',
  'Shangqiu',
  'Shangrao',
  'Shangzhi',
  'Shangzhou',
  'Shanhu',
  'Shantou',
  'Shanwei',
  'Shaoguan',
  'Shaowu',
  'Shaoxing',
  'Shaoyang',
  'Shaoyang',
  'Sharjah',
  'Sheffield',
  'Shekhupura',
  'Shengli',
  'Shenmu',
  'Shenyang',
  'Shenzhen',
  'Shenzhou',
  'Shibuya-ku',
  'Shihezi',
  'Shijiazhuang',
  'Shiliguri',
  'Shimla',
  'Shimoga',
  'Shinagawa-ku',
  'Shinjuku',
  'Shinozaki',
  'Shiraz',
  'Shishi',
  'Shiyan',
  'Shizuoka',
  'Shouguang',
  'Shreveport',
  'Shuanghejiedao',
  'Shuangqiao',
  'Shuangyashan',
  'Shubra al Khaymah',
  'Shuizhai',
  'Shulan',
  'Shuozhou',
  'Shuyangzha',
  'Shymkent',
  'Sialkot City',
  'Sibu',
  'Sidi Bel Abbes',
  'Sidi Bouzid',
  'Sihui',
  'Sihung',
  'Sikar',
  'Sikasso',
  'Silang',
  'Simferopol',
  'Sincelejo',
  'Singapore',
  'Singaraja',
  'Singkawang',
  'Sintra',
  'Sinuiju',
  'Siping',
  'Sizhan',
  'Skopje',
  'Smolensk',
  'Soacha',
  'Soc Trang',
  'Sochi',
  'Sofia',
  'Soka',
  'Sokoto',
  'Solapur',
  'Soledad',
  'Soledad de Graciano Sanchez',
  'Solihull',
  'Songnam',
  'Songyang',
  'Songzi',
  'Sonipat',
  'Sorocaba',
  'Sorong',
  'Sousse',
  'South Bend',
  'Southampton',
  'Soweto',
  'Spokane',
  'Spring Valley',
  'Springfield',
  'Springfield',
  'Springs',
  'Srinagar',
  'St. Catharines',
  'St. Louis',
  'St. Paul',
  'St. Petersburg',
  'Staryy Oskol',
  'Staten Island',
  'Stavropol',
  'Sterlitamak',
  'Stockholm',
  'Stockton',
  'Stoke-on-Trent',
  'Strasbourg',
  'Stuttgart',
  'Sucre',
  'Suez',
  'Suginami-ku',
  'Suihua',
  'Suining',
  'Sukabumi',
  'Sukkur',
  'Sumare',
  'Sumbe',
  'Sumida',
  'Sumqayit',
  'Sumy',
  "Sunch'on",
  'Suncheon',
  'Sunderland',
  'Sungai Petani',
  'Suohe',
  'Suoluntun',
  'Suqian',
  'Surabaya',
  'Surakarta',
  'Surat',
  'Surgut',
  'Surrey',
  'Suwon',
  'Suzano',
  'Suzhou',
  'Suzhou',
  'Swindon',
  'Sydney',
  'Syktyvkar',
  'Sylhet',
  'Syracuse',
  'Szczecin',
  'Ta`izz',
  'Taboao da Serra',
  'Tabriz',
  'Tabuk',
  'Tacloban',
  'Tacna',
  'Tacoma',
  'Taganrog',
  'Taguig City',
  'Tagum',
  "Tai'an",
  'Taichung',
  'Taihe',
  'Taihecun',
  'Tainan',
  'Taipei',
  'Taiping',
  'Taiping',
  'Taishan',
  'Taisheng',
  'Taito',
  'Taixing',
  'Taiyuan',
  'Taizhou',
  'Taizhou',
  'Takamatsu',
  'Takarazuka',
  'Takasaki',
  'Takatsuki',
  'Talatona',
  'Talca',
  'Talisay',
  'Tallahassee',
  'Tallinn',
  'Taluqan',
  'Tamale',
  'Tambov',
  'Tampa',
  'Tampere',
  'Tampico',
  'Tanbei',
  "Tanch'on",
  'Tanga',
  'Tangdong',
  'Tangerang',
  'Tangier',
  'Tangshan',
  'Tanjore',
  'Tanjungpinang',
  'Tanta',
  'Tanza',
  'Taourirt',
  'Taoyuan District',
  'Taozhou',
  'Tapachula',
  'Tarakan',
  'Tarapoto',
  'Taraz',
  'Tarlac City',
  'Tarrasa',
  'Tashkent',
  'Tasikmalaya',
  'Taubate',
  'Taytay',
  'Tbilisi',
  'Tecamac',
  'Tegal',
  'Tegucigalpa',
  'Tehran',
  'Tehuacan',
  'Tekirdag',
  'Tel Aviv-Yafo',
  'Temara',
  'Temuco',
  'Tengyue',
  'Tepic',
  'Teresina',
  'Ternate',
  'Ternopil',
  'Tetouan',
  'Thai Binh',
  'Thai Nguyen',
  'Thane',
  'Thanh Hoa',
  'The Hague',
  'Thessaloniki',
  'Thies',
  'Thiruvananthapuram',
  'Thousand Oaks',
  'Thu Dau Mot',
  'Thu Duc',
  'Tianchang',
  'Tianjin',
  'Tieli',
  'Tieling',
  'Tijuana',
  'Tilburg',
  'Timbio',
  'Timisoara',
  'Tinnevelly',
  'Tirana',
  'Tiruppur',
  'Tlajomulco de Zuniga',
  'Tlalnepantla',
  'Tlaquepaque',
  'Toamasina',
  'Tokat',
  'Tokorozawa',
  'Tokushima',
  'Tokyo',
  'Toledo',
  'Toledo',
  'Toluca',
  'Tolyatti',
  'Tomsk',
  'Tonala',
  'Tongchuan',
  'Tongchuanshi',
  'Tongliao',
  'Tongren',
  'Tongshan',
  'Toronto',
  'Torreon',
  'Torun',
  'Toshima',
  'Touba',
  'Toulouse',
  'Toyama',
  'Toyohashi',
  'Toyonaka',
  'Toyota',
  'Trece Martires City',
  'Trenton',
  'Trichinopoly',
  'Trichur',
  'Trieste',
  'Tripoli',
  'Tripoli',
  'Trujillo',
  'Tshikapa',
  'Tsu',
  'Tsukuba-kenkyugakuen-toshi',
  'Tucson',
  'Tula',
  'Tulsa',
  'Tultitlan de Mariano Escobedo',
  'Tulua',
  'Tumkur',
  'Tunis',
  'Tunja',
  'Turin',
  'Turkmenabat',
  'Turmero',
  'Turpan',
  'Tuticorin',
  'Tuxtla',
  'Tuy Hoa',
  'Tver',
  'Tyumen',
  'Uberaba',
  'Uberlandia',
  'Udaipur',
  'Ufa',
  'Uige',
  'Uijeongbu',
  'Ujjain',
  'Ulaanbaatar',
  'Ulan-Ude',
  'Ulanhot',
  'Ulhasnagar',
  'Ulsan',
  'Uluberiya',
  'Ulyanovsk',
  'Umuahia',
  'Uruapan',
  'Urumqi',
  'Usulutan',
  'Utrecht',
  'Utsunomiya',
  'Uyo',
  'Vadodara',
  'Valencia',
  'Valencia',
  'Valencia',
  'Valenzuela',
  'Valladolid',
  'Valledupar',
  'Valparaiso',
  'Van',
  'Vancouver',
  'Vantaa',
  'Varamin',
  'Varanasi',
  'Varna',
  'Varzea Grande',
  'Vaughan',
  'Velikiy Novgorod',
  'Venice',
  'Veracruz',
  'Vereeniging',
  'Verona',
  'Viamao',
  'Victoria',
  'Victorville',
  'Vienna',
  'Vientiane',
  'Viet Tri',
  'Vigo',
  'Vila Nova de Gaia',
  'Vila Teixeira da Silva',
  'Vila Velha',
  'Vila Velha',
  'Villa Nueva',
  'Villahermosa',
  'Villavicencio',
  'Vilnius',
  'Vina del Mar',
  'Vinh',
  'Vinnytsia',
  'Virginia Beach',
  'Visalia',
  'Vishakhapatnam',
  'Vitoria',
  'Vitoria da Conquista',
  'Vitoria-Gasteiz',
  'Vitsyebsk',
  'Vizianagaram',
  'Vladikavkaz',
  'Vladimir',
  'Vladivostok',
  'Volgograd',
  'Vologda',
  'Volta Redonda',
  'Volzhskiy',
  'Voronezh',
  'Vung Tau',
  'Wad Medani',
  'Wafangdian',
  'Waitakere',
  'Wakayama',
  'Wancheng',
  'Warangal',
  'Warnes',
  'Warri',
  'Warsaw',
  'Washington',
  'Weichanglu',
  'Weifang',
  'Weihai',
  'Weinan',
  'Welkom',
  'Wellington',
  'Wenchang',
  'Wencheng',
  'Wenlan',
  'Wenling',
  'Wenzhou',
  'Westminster',
  'Wichita',
  'Wiesbaden',
  'Wilmington',
  'Windhoek',
  'Windsor',
  'Winnipeg',
  'Winston-Salem',
  'Winter Haven',
  'Wollongong',
  'Wolverhampton',
  'Wonju',
  'Wonsan',
  'Worcester',
  'Wroclaw',
  "Wu'an",
  'Wuchuan',
  'Wudalianchi',
  'Wugang',
  'Wuhai',
  'Wuhan',
  'Wuhu',
  'Wuppertal',
  'Wusong',
  'Wutong',
  'Wuwei',
  'Wuxi',
  'Wuxue',
  'Wuyishan',
  'Wuzhong',
  'Wuzhou',
  'Xalapa',
  "Xi'an",
  'Xiamen',
  'Xiangshui',
  'Xiangtan',
  'Xiangxiang',
  'Xiangyang',
  'Xiangyang',
  'Xiantao',
  'Xianyang',
  'Xiaoganzhan',
  'Xiaoxita',
  'Xiaoyi',
  'Xibeijie',
  'Xichang',
  'Xicheng',
  'Xigaze',
  'Ximeicun',
  "Xin'an",
  'Xindi',
  'Xingcheng',
  'Xingcheng',
  'Xingren',
  'Xingtai',
  'Xingyi',
  'Xinhualu',
  'Xining',
  'Xinji',
  'Xinmin',
  'Xinpu',
  'Xinshi',
  'Xintai',
  'Xinxing',
  'Xinyang',
  'Xinyi',
  'Xinyu',
  'Xinzhou',
  'Xiping',
  'Xiping',
  'Xishan',
  'Xiulin',
  'Xuanzhou',
  'Xushan',
  'Yachiyo',
  'Yakeshi',
  'Yakou',
  'Yakutsk',
  'Yamagata',
  'Yamoussoukro',
  "Yan'an",
  "Yan'an Beilu",
  'Yanbu`',
  'Yancheng',
  'Yangchun',
  'Yanggok',
  'Yangjiang',
  'Yangquan',
  'Yangsan',
  'Yangshe',
  'Yangzhou',
  'Yanji',
  'Yanjiang',
  'Yanjiao',
  'Yantai',
  'Yao',
  'Yaounde',
  'Yaroslavl',
  'Yato',
  'Yatou',
  'Yazd',
  'Yekaterinburg',
  'Yeosu',
  'Yeosu',
  'Yerevan',
  'Yibin',
  'Yicheng',
  'Yicheng',
  'Yichun',
  'Yichun',
  'Yidu',
  'Yildirim',
  'Yinchuan',
  'Yingcheng',
  'Yingchuan',
  'Yingkou',
  'Yingmen',
  'Yingtan',
  'Yingzhong',
  'Yiwu',
  'Yiyang',
  'Yiyang',
  'Yogyakarta',
  'Yokkaichi',
  'Yokohama',
  'Yokosuka',
  'Yola',
  "Yong'an",
  'Yongcheng',
  'Yongji',
  'Yongzhou',
  'Yonkers',
  'York',
  'Yoshkar-Ola',
  'Youngstown',
  'Yuanping',
  'Yucheng',
  'Yucheng',
  'Yuci',
  'Yueqing',
  'Yulin',
  'Yulinshi',
  'Yuncheng',
  'Yunfu',
  'Yunzhong',
  'Yushan',
  'Yushu',
  'Yutan',
  'Yuxi',
  'Yuyao',
  'Zagreb',
  'Zahedan',
  'Zakhu',
  'Zalantun',
  'Zamboanga City',
  'Zamora',
  'Zanjan',
  'Zanzibar',
  'Zaoyang',
  'Zaozhuang',
  'Zapopan',
  'Zaporizhzhia',
  'Zaragoza',
  'Zaria',
  'Zarzal',
  'Zhangjiajie',
  'Zhangjiakou',
  'Zhangjiakou Shi Xuanhua Qu',
  'Zhangping',
  'Zhangshu',
  'Zhangye',
  'Zhangzhou',
  'Zhanjiang',
  'Zhaodong',
  'Zhaoqing',
  'Zhaotong',
  'Zhengjiatun',
  'Zhengzhou',
  'Zhenjiang',
  'Zhenzhou',
  'Zhijiang',
  'Zhongba',
  'Zhongli',
  'Zhongshan',
  'Zhongshu',
  'Zhongwei',
  'Zhongxiang',
  'Zhoukou',
  'Zhoushan',
  'Zhuanghe',
  'Zhuangyuan',
  'Zhufeng',
  'Zhuhai',
  'Zhuji',
  'Zhumadian',
  'Zhuozhou',
  'Zhuzhou',
  'Zhytomyr',
  'Zibo',
  'Zigong',
  'Ziguinchor',
  'Zijinglu',
  'Zinder',
  'Zouping',
  'Zunhua',
  'Zunyi',
  'Zurich',
  '`Ajman'
];
List<String> countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  "Cote d'Ivoire",
  'Country-less Wanderer',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Lao',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States of America',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe'
];
List<String> languages = [
  'Afrikaans',
  'Albanian',
  'Arabic',
  'Armenian',
  'Basque',
  'Bengali',
  'Bulgarian',
  'Cambodian',
  'Catalan',
  'Chinese (Mandarin)',
  'Croatian',
  'Czech',
  'Danish',
  'Dutch',
  'English',
  'Estonian',
  'Fiji',
  'Finnish',
  'French',
  'Georgian',
  'German',
  'Greek',
  'Gujarati',
  'Hebrew',
  'Hindi',
  'Hungarian',
  'Icelandic',
  'Indonesian',
  'Irish',
  'Italian',
  'Japanese',
  'Javanese',
  'Korean',
  'Latin',
  'Latvian',
  'Lithuanian',
  'Macedonian',
  'Malay',
  'Malayalam',
  'Maltese',
  'Maori',
  'Marathi',
  'Mongolian',
  'Nepali',
  'Norwegian',
  'Persian',
  'Polish',
  'Portuguese',
  'Punjabi',
  'Quechua',
  'Romanian',
  'Russian',
  'Samoan',
  'Serbian',
  'Sicilian',
  'Slovak',
  'Slovenian',
  'Spanish',
  'Swahili',
  'Swedish',
  'Tamil',
  'Tatar',
  'Telugu',
  'Thai',
  'Tibetan',
  'Tonga',
  'Turkish',
  'Ukrainian',
  'Urdu',
  'Uzbek',
  'Vietnamese',
  'Welsh',
  'Xhosa'
];
