import 'dart:math';
import 'package:flutter/material.dart';

const keyApplicationId = 'xhYBShLQtWSlLo4BmLdK0QKvHiSFjwsAE36DeWnf';
const keyClientKey = '4gn52E4GHQDZOuDYQgw53YJpsBTcR8Yh6Fu5k1fQ';
const keyParseServerUrl = 'https://parseapi.back4app.com';

const searchIndex = 2;
const messagesIndex = 3;
const eventsIndex = 1;
const profileIndex = 0;

const appName = "SKILLOGUE";

const loggedProfileKey = 0;

const newFunctionalityMessage =
    "Everyone wants the moon, but you gotta wait for this functionality! :-)";

Color getRandomDarkColor() {
  Color randomColor =
      Color((Random().nextDouble() * 0xFFFFFF).toInt()).withOpacity(1.0);
  if (randomColor.computeLuminance() < 0.250) {
    return randomColor;
  } else {
    return getRandomDarkColor();
  }
}

TextStyle getWhiteTextStyle() {
  return const TextStyle(color: Colors.white);
}

Color getLightBlue() {
  return const Color.fromRGBO(179, 217, 248, 0);
}

List<String> countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  "Cote d'Ivoire",
  'Country-less Wanderer',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Lao',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States of America',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe'
];
List<String> languages = [
  'Afrikaans',
  'Albanian',
  'Arabic',
  'Armenian',
  'Basque',
  'Bengali',
  'Bulgarian',
  'Cambodian',
  'Catalan',
  'Chinese (Mandarin)',
  'Croatian',
  'Czech',
  'Danish',
  'Dutch',
  'English',
  'Estonian',
  'Fiji',
  'Finnish',
  'French',
  'Georgian',
  'German',
  'Greek',
  'Gujarati',
  'Hebrew',
  'Hindi',
  'Hungarian',
  'Icelandic',
  'Indonesian',
  'Irish',
  'Italian',
  'Japanese',
  'Javanese',
  'Korean',
  'Latin',
  'Latvian',
  'Lithuanian',
  'Macedonian',
  'Malay',
  'Malayalam',
  'Maltese',
  'Maori',
  'Marathi',
  'Mongolian',
  'Nepali',
  'Norwegian',
  'Persian',
  'Polish',
  'Portuguese',
  'Punjabi',
  'Quechua',
  'Romanian',
  'Russian',
  'Samoan',
  'Serbian',
  'Sicilian',
  'Slovak',
  'Slovenian',
  'Spanish',
  'Swahili',
  'Swedish',
  'Tamil',
  'Tatar',
  'Telugu',
  'Thai',
  'Tibetan',
  'Tonga',
  'Turkish',
  'Ukrainian',
  'Urdu',
  'Uzbek',
  'Vietnamese',
  'Welsh',
  'Xhosa'
];
List<String> skills = [
  'Acting',
  'Animals',
  'Archeology',
  'Architecture',
  'Art',
  'Backpacking',
  'Bird watching',
  'Calligraphy ',
  'Camping',
  'Cinema',
  'Climbing',
  'Clubbing',
  'Cocktails',
  'Comics',
  'Computer Science',
  'Cooking',
  'Crochet',
  'Culture Exchange',
  'Cycling ',
  'Dancing',
  'Design',
  'Drawing',
  'Drugs',
  'Embroidery',
  'Engineering ',
  'Entomology',
  'Entrepreneurship ',
  'Fashion',
  'Fencing',
  'Fishing',
  'Football',
  'Gardening',
  'Geology',
  'Golf',
  'Guitar',
  'Gym',
  'Hiking',
  'History',
  'Horse Riding',
  'Hunting',
  'Jewellery making',
  'Jogging',
  'Kayaking',
  'Knitting',
  'Language Exchange',
  'Literature',
  'Maths',
  'Motorbikes',
  'Movies',
  'Museums',
  'Music',
  'Nature',
  'Painting',
  'Photography',
  'Piano',
  'Politics',
  'Psychology',
  'Reading',
  'Role-playing',
  'Running',
  'Sailing',
  'Science',
  'Shooting',
  'Skiing',
  'Smiting',
  'Socializing',
  'Spirituality',
  'Sport',
  'Sustainability',
  'Swimming',
  'Taxidermy',
  'Theatre',
  'Translation',
  'Traveling',
  'Video Editing',
  'Volunteering',
  'Walking',
  'Wood carving',
  'Yoga'
];
List<String> genders = ["Male", "Female", "Other"];

const STANDARD_OPACITY = 0.35;
TextStyle textFieldStyleWithOpacity =
    TextStyle(color: Colors.grey.withOpacity(0.9));
